# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    main_controller:
        class: AppBundle\Controller\DefaultController
        arguments: ["@doctrine.odm.mongodb.document_manager", "@logger"]
