# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    main_controller:
        class: CrawlerBundle\Controller\DefaultController
        arguments: ["@?doctrine_mongodb.odm.document_manager", "@logger"]
